# Generated by Django 5.2.8 on 2026-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Адрес доставки, который будет использован курьером', max_length=500, null=True, verbose_name='Адрес доставки'),
        ),
    ]
